"""Produce an immutable, allowlisted source ZIP; generated bytecode is excluded."""
from pathlib import Path
import argparse
import hashlib
import json
import zipfile

def main():
    p=argparse.ArgumentParser();p.add_argument('output');p.add_argument('--backend-only',action='store_true');a=p.parse_args()
    root=Path(__file__).resolve().parents[1];output=Path(a.output).resolve()
    if output.exists():raise FileExistsError(output)
    owned={'app.py','widgets.py','platform_support.py','label_catalog.py','label_logic.py','test_label_logic_v012.py','i18n.py'}
    files=[]
    for folder in ('annotation_app','tests','tools','examples/synthetic-v1','schemas','docs','.github'):
        for path in (root/folder).rglob('*'):
            if path.is_file() and '__pycache__' not in path.parts and path.suffix not in ('.pyc','.sqlite','.db'):
                if a.backend_only and (path.name in owned or 'translations' in path.parts):continue
                files.append(path)
    for name in ('IMPLEMENTATION.md','SOURCE_ORIGIN.json','pyproject.toml','LICENSE','NOTICE','README.md','mkdocs.yml','.gitignore','CITATION.cff','CHANGELOG.md','CONTRIBUTING.md','THIRD_PARTY_NOTICES.md'):
        if (root/name).is_file():files.append(root/name)
    records=[]
    with zipfile.ZipFile(output,'x',compression=zipfile.ZIP_DEFLATED,compresslevel=6) as archive:
        for path in sorted(files):
            relative=path.relative_to(root).as_posix();data=path.read_bytes()
            archive.writestr(relative,data)
            records.append({'path':relative,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
        archive.writestr('HANDOFF-FILES.json',json.dumps(records,indent=2))
    print(json.dumps({'path':str(output),'bytes':output.stat().st_size,'sha256':hashlib.sha256(output.read_bytes()).hexdigest(),'files':len(records)}))

if __name__=='__main__':main()
